INSERT INTO "Size" ("name", "isActive", "createdAt", "updatedAt")
VALUES
    ('XXS', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('XS', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('XXL', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('3XL', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('34', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('36', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('38', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('40', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('42', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('44', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('46', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Tek Beden', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("name") DO NOTHING;

INSERT INTO "Color" ("name", "isActive", "createdAt", "updatedAt")
VALUES
    ('Sarı', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Turuncu', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Mor', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Pembe', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Kahverengi', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Bordo', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Bej', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Füme', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Altın', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Rose Gold', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT ("name") DO NOTHING;
